### ISSUE TITLE
Add option to restrict AWS accounts for Privatelink-enabled deployments

### ISSUE THREAD

**Issue by abhinavg6** [wandb/terraform-aws-wandb#174]
AWS Privatelink support was added as part of this PR - https://github.com/wandb/terraform-aws-wandb/pull/169

We would like to provide an option with Privatelink-enabled deployments to restrict private access to specific AWS accounts only - https://docs.aws.amazon.com/vpc/latest/privatelink/configure-endpoint-service.html. This is required so a rogue user in a company couldn't create a private endpoint to their deployment from their personal AWS account and exfiltrate company data.

**Comment by wandb-zacharyblasczyk** [comment]
`private_link_allowed_account_ids` is the only way to enable Private Link and [this](https://github.com/wandb/terraform-aws-wandb/pull/169/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR173) specifically locks it down to the individual aws accounts.

**Comment by abhinavg6** [comment]
Aah ok. So we could close this then? I think I asked you internally too and you had shares this, so my apologies.
