### ISSUE TITLE
Allow version pinning in Operator-based deployments

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#264]
Description

Today: Self-managed customers have multiple stages/environments. When using operator, a customer can not pin the version they want to roll out to a specific environment as W&B does the rollout. In a non-Operator based deployment, version pinning was supported.

Expectation: Customers can decide when to roll out a new W&B Server version to an environment. Version pinning should be possible in the console UI without the need of YAML, e.g. a dropdown box containing “latest”, “0.57”, 0.56”, etc.

**Comment by abhinavg6** [comment]
Removing it from here since @zacharyblasczyk is already working on a relevant project.
