### ISSUE TITLE
Support Matrix and Supported Configurations in Public Docs

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#266]
Today: We do have very limited information on our public docs about supported configurations and installation requirements. The information that exists is distributed across several pages.

Expectations: A central place that customers can access and find all information about supported configurations and installation requirements.

Examples:

Terraform Enterprise https://developer.hashicorp.com/terraform/enterprise/flexible-deployments/install 

JBoss EAP: https://access.redhat.com/articles/2026253

Example link: Like oracle, we can simply note that certain configurations are untested yet.

[Compatibility Matrix](https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengCompatibilitymatrix_topic.htm)

**Comment by abhinavg6** [comment]
IMO this needs to be partially owned by the SA/SMLE team along with Eng & Docs (like how Marc had owned the last significant update). This is not something that consultants can or should do.

**Comment by abhinavg6** [comment]
I'm removing this from consultants queue.
