### ISSUE TITLE
Operator console User Spec tab don't keep the configuration

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#269]
If you change the window, the User Spec tab does not keep the content while you’re editing. 

There’s no fix for this. We had to copy the configuration we wanted, stage in a txt, fix whatever was needed, and past in the User Spectab

https://github.com/user-attachments/assets/b2e65f90-9f29-42f8-b1bf-5f0d5333febc

**Comment by abhinavg6** [comment]
Let's retest plz

**Comment by abhinavg6** [comment]
@flamarion - Were you able to retest it?

**Comment by abhinavg6** [comment]
Closing as per chat on 9/16
