### ISSUE TITLE
WSM - Download ALL Images

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#271]
When using the option wsm deploy, download all necessary images as if the customer were using all possible components without any connectivity with the external world.

This will allow customers to push these messages to their internal registries and pull them from eventual changes in the deployment.

If they do not use it, they can discard them, but they must have the option to do such an operation.

**Comment by abhinavg6** [comment]
This exact issue can be closed - a nice to have FR to list out all the images to be created by @flamarion separately
