### ISSUE TITLE
Feature Request Operator | Support to pull Redis credentials from secrets in the CR

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#285]
Description

Add support to pull REDIS credentials from Secrets when deploying CRD from yaml file.

[helm-charts/charts/operator-wandb/values.yaml at main · wandb/helm-charts](https://github.com/wandb/helm-charts/blob/main/charts/operator-wandb/values.yaml#L103-L108)

  redis:
    host: ""
    port: 6379
    password: ""
    parameters: {}
    caCert: ""

This can be the entire configuration or at least the password pulled from secrets

env:
  - name: REDIS_PASS
    valueFrom:
      secretKeyRef:
        name: redis-data
        key: redis-pass

  redis:
    host: ""
    port: 6379
    password: $(REDIS_PASS)
    parameters: {}
    caCert: ""

**Comment by velotioaastha** [comment]
https://github.com/wandb/helm-charts/pull/223

**Comment by abhinavg6** [comment]
PR from @danielpanzella - https://github.com/wandb/helm-charts/pull/229

Let's plz close this issue once that is approved & merged. Thanks.
