### ISSUE TITLE
Feature Request Operator | WSM - List Images instead of download

### ISSUE THREAD

**Issue by vijay-wandb** [wandb/terraform-aws-wandb#293]
Description

Given that we download the charts and images, how do we expect to load the images to the Kubernetes nodes if one doesn’t have the internal registry?

Actually, the main question is: Why do we download the images?

Assuming wsm will not do the thing to load the images in the K8s nodes and with the expectation that all customers must have an internal registry in their airgapped environment that can be set in the values.yamlwe could only download the charts,  list the images along with a message like:

**“These are the images you need to deploy W&B, make it available somewhere and configure the values.yaml”**

**Comment by flamarion** [comment]
The message is only a suggestion; please consider replacing `somewhere` with `internal container registry.`
