### ISSUE TITLE
Not operator | Validate EKS 1.29 upgrade

### ISSUE THREAD

**Issue by abhinavg6** [wandb/terraform-aws-wandb#297]
@zacharyblasczyk has [this PR](https://github.com/wandb/terraform-aws-wandb/pull/296) for 1.29 upgrade. We've to get that in and upgrade the Dedicated Cloud fleet by mid-Nov. Would it be possible to have another pair of eyes at that and validate if that's good or if other changes may be needed?

**Comment by zacharyblasczyk** [comment]
I am closing this for now. I think there are more important things to work on and we already have this in the QA env.
