### ISSUE TITLE
No way to provide license?

### ISSUE THREAD

**Issue by uberbrodt** [wandb/terraform-aws-wandb#30]
examples show a license var I can set but it does not appear in the source for the module

**Comment by uberbrodt** [comment]
ah ok. thanks. Is there a guide I should be following? I find references to the old terraform but not much for the new stuff

**Comment by jsbroks** [comment]
@uberbrodt sorry for the late response here.

We do have some examples you can find [here](https://github.com/wandb/terraform-aws-wandb/tree/main/examples) that show you how to provision both modules. We do not much documentation, but we will be actively adding more in the coming weeks
