### ISSUE TITLE
[private-access-only]An argument named "wandb_license" is not expected here

### ISSUE THREAD

**Issue by Belyenochi** [wandb/terraform-aws-wandb#37]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/26409132/191932836-a84863f0-f326-47e9-b853-1deae8301826.png">

**Comment by Belyenochi** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/26409132/192078989-ad681953-8a1e-4833-8c73-6cfc1a3349b6.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/26409132/192078997-96e4c79b-24c9-432b-8b7e-c456597b7397.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/26409132/192078982-bfbbf910-7c91-4af0-ae61-63163fefc8d3.png">

**Comment by jsbroks** [comment]
Looks like we forgot to add a variable for wandb_license! Sorry about that. We have not extensively tested the private version. I would recommend using the public example, and setting allows list CIDR ranges to limit access only from within your vpn.

**Comment by Belyenochi** [comment]
> Looks like we forgot to add a variable for wandb_license! Sorry about that. We have not extensively tested the private version. I would recommend using the public example, and setting allows list CIDR ranges to limit access only from within your vpn.

hey @jsbroks thank you for your reply, we tried to use the publi-dns-externel of the master branch, but encountered the following error when applying terraform, looking forward to your reply.

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/26409132/192926692-e32e10f8-5a43-4209-9b0d-d6949df47c71.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/26409132/192926828-f1bdad92-bc3f-4fba-81d2-92db70359d62.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/26409132/192927060-24b8fec6-8a03-49ae-9412-18af42f3ddf5.png">

**Comment by Belyenochi** [comment]
terraform-aws-wandb version: v1.5.3
